[package]
name = "nametag"
version = "0.1.28"
authors = ["sts10 <sschlinkert@gmail.com>"]
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
rand = "0.8.5"
clap = { version = "4.4.2", features = ["derive"] }
