[package]
name = "nametag"
version = "0.1.31"
edition = "2021"
authors = ["sts10 <sschlinkert@gmail.com>"]
license = "AGPL-3.0-only"
readme = "readme.markdown"
repository = "https://github.com/sts10/nametag"

[dependencies]
rand = "0.8.5"
clap = { version = "4.4.2", features = ["derive"] }
